### ISSUE TITLE
$watch doesnt get executed for hidden fields in angular formly

### ISSUE THREAD

**Issue by hrishi1183** [formly-js/angular-formly-website#59] opened 2015-07-28 15:01 UTC
$watch is ignoring the hidden fields while working on the list of fields..
see the below jsbin,
http://jsbin.com/riwaku/edit?js,console,output

if Add an Applicant is deselected .. it should clear the firstname field so that when use select it again.. firstName comes in its default state.. but $watch is ignoring to clear the value because it gets hidden before $watch execution hence got ignored

**Comment by kentcdodds** [comment] 2015-07-28 15:32
Yeah, this is a performance optimization. However you could try the [`hide-directive`](http://docs.angular-formly.com/v6.21.0/docs/formly-form) feature.

Or, you could go about it a much different way: https://jsbin.com/cagawe/edit?html,js,console,output

But this is not a bug, it's a feature :-) Thanks for using formly. I'm going to go ahead and close this, but feel free to chat back if you have questions.

**Closed as completed** 2015-07-28 15:33 UTC
