### ISSUE TITLE
Translate placeholder, Text

### ISSUE THREAD

**Issue by hmendezm** [formly-js/angular-formly-website#76] opened 2015-09-08 13:04 UTC
Hi Guys

This formly stuff is awesome!

I have the following situation: I am working for international organization where multilingual feature is very important. 

we have a form the work great with angular-translate but when I try to implement formly/formly-templates it does not translate. It translated if I chose first the languages and after load the view. in my case users can change language in fly. I have three buttons EN, ES, and FR. When the user click ES the UI change to SPANISH for example.

My configuration for angular-translate is

```
.config(function($translateProvider) {
               $translateProvider.useSanitizeValueStrategy('escape');
               $translateProvider.useStaticFilesLoader({ prefix: '/languages/', suffix: '.json' });
               $translateProvider.preferredLanguage('en-US');
    })
```

and in the field declaration I have

```
$scope.companyFields = [
        {
            key: 'company_name',
            type: 'input',
            templateOptions: {
                type: 'text',
                label:  $translate.instant('TXT_COMPANYNM'),
                placeholder: $translate.instant('TXT_COMPANYPH'),
                required: true
            },
                expressionProperties: {
                        'templateOptions.label': '"TXT_COMPANYNM" | translate',
                        'templateOptions.placeholder': '"TXT_COMPANYPH" | translate'
                }
        }, (..)
```

The other situintion related to translation is the following

We have in the database tables for translate the data itself so the webapi return the translations in json form and in the view we use something like the html code below. How can I convert this to formly.

```
 <div class="form-group">
     <label class="col-md-4 control-label" for="sProduct">All your products/Services*</label>
         <div class="col-md-4">
             <select class="form-control" ng-model="assesstment.Product" ng-options="product.id as product.translations[getLanguageID(product.translations,selectedLanguageCode,'language_id')].name for product in products" >  
             </select>  
           </div>
  </div>

NOTE: getLanguageID(array,language selected in the UI) is a function the return a valid language code to be translate.
```

I really wanto use this. But I want to be sure that I can do this in Formly. I hope that I can do it because this really make easier the development process of forms.

best regards
H.

**Comment by kentcdodds** [comment] 2015-09-08 13:08
Have you seen the [angular-translate integration example](http://angular-formly.com/#/example/integrations/angular-translate)? You can definitely do what you're trying to do. I'm not sure what the issue is. If you need help, I recommend you follow the instructions here: http://help.angular-formly.com

Either way, the GitHub issues on this repo is not the place for questions. Please follow those instructions :point_up_2: I'm going to go ahead and close this. Good luck!

**Closed as completed by kentcdodds** 2015-09-08 13:08 UTC

**Comment by hmendezm** [comment] 2015-09-08 14:41
Hi Kent
Thanks for your reply
the problem is the text is not change when the user click the language that s/he wants to see.  

Yes, I checked the example but in my case I am using json file. Also, if you check your example, the radio buttons are not translate when I choose one language. 

Do you have a example using json file?

Where should I enter my questions?

best Regards
H.

**Comment by kentcdodds** [comment] 2015-09-08 14:43
If you go to: http://help.angular-formly.com there will be instructions there.

**Comment by hmendezm** [comment] 2015-09-10 12:40
Hi Kent

I used the example that you have (angular-translate integration example) and make a littler change to reproduce my problem.

I found that the problem is that user change languages outside the formly directive and the controls inside the formly directive is not update. My guess is something with the watcher that they share. 

You will find to groups of radio buttons for language selection. One is outside of the directive which is not update/refresh the text inside formly directive and the other is inside which work perfectly.

Please see my example of the problem that I have.
http://jsbin.com/hahako/edit?html,js,output

Thanks for all your help!
Best Regards
H

**Comment by kentcdodds** [comment] 2015-09-10 13:03
It looks like your `newVal` function isn't getting called when you change the language. I don't have time to look into why, but you may want to get that working first.

**Comment by hmendezm** [comment] 2015-09-11 08:28
Hi Kent,

I fixed the newVal function now it is getting so you can see my problem.

Best Regard
H.

**Comment by kentcdodds** [comment] 2015-09-11 15:45
There were a few problems with your solution.
1. You weren't passing the value back to the `newVal` function. You were passing `value`, when it should have been `vm.value`.
2. angular-formly runs those `expressionProperties` when the `model` or `formState` changes. So you have three choices. You can either iterate over the fields and run them yourself (I have commented out code for that), you can update the `formState` manually, or, **the best approach** is to use `Object.defineProperty` to define the `lang` to `get` and `set` with `$translate.use`. I chose the later. But if you have to support IE8 you might have a hard time.

Let me know if that helps you!
